services:
  flask-todo-app:
    build: . # . means current directory
    develop:
      watch:
        - action: sync # syncs the local path and target path
          path: . # . means current directory
          target: /code
          ignore: # ignore files that we don't want to sync
            - Dockerfile 
        - action: rebuild # rebuilds the container triggers when requirements.txt is modified and saved.
          path: requirements.txt 
    ports: 
      - 8000:5000
  
  mysql:
    image: mysql:8.0 # image is from docker hub, using version 8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
